name        : Taye - Here I am
baseurl     : /blog
pygments    : true
timezone    : Europe/Dublin

markdown    : redcarpet
redcarpet:
      extensions: [tables, laxed_spacing, fenced_code_blocks, strikethrough, autolink, superscript, no_intra_emphasis]
