name        : Taye - Here I am
description : Taye Adeyemi - Programmer · Visionary · Delicious
baseurl     : /blog
url         : http://taye.me/blog
pygments    : true
timezone    : Europe/Dublin

markdown    : redcarpet
redcarpet:
      extensions: [tables, laxed_spacing, fenced_code_blocks, strikethrough, autolink, superscript, no_intra_emphasis, with_toc_data]
