name        : Here I am - Taye Adeyemi
description : Taye Adeyemi - Programmer · Visionary · Delicious
baseurl     : /brog/_site
url         : http://taye.me/brog/_site
pygments    : true
timezone    : Europe/Dublin

markdown    : redcarpet
redcarpet:
      extensions: [tables, laxed_spacing, fenced_code_blocks, strikethrough, autolink, superscript, no_intra_emphasis, with_toc_data]
